### ISSUE TITLE
NX-OS learn OSPF Missing keys error

### ISSUE THREAD

**Issue by spasekovachev** [CiscoTestAutomation/genielibs#134]
I've run into the issue when I try to read/learn OSPF from a NK9 (NX-OS) which has been configured with segment routing.

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/site-packages/genie/libs/ops/ospf/nxos/ospf.py", line 1044, in learn
    self.make(final_call=True)
  File "/site-packages/genie/ops/base/base.py", line 103, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 315, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 427, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 342, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 322, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 419, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys:

**Comment by SohanTirpude** [comment]
Hello @spasekovachev,

I will be working on this issue. But before that, kindly let me know if this is the command that you used: `genie learn ospf --testbed-file /path/to/testbed.yaml --devices nx-osv --output genie_learn` OR if it is different then kindly share me with that. 

Thank you.

**Comment by spasekovachev** [comment]
Hello, 

thanks for taking care of the issue.
I used the Lookup class from the genie.abstract module.

            _abstract = Lookup.from_device(dev)
            ospf = abstract.ops.ospf.ospf.Ospf(dev)
            ospf.learn('default')_

But I've got the same output with the command you suggested
 Thanks you.

**Comment by SohanTirpude** [comment]
Hello @spasekovachev,

Ok, thanks for the confirmation that you are seeing this issue with command as well. Kindly give me some time to analyse and debug the issue.

Thank you.

**Comment by SohanTirpude** [comment]
Hello @spasekovachev,

Can you please share me the whole error log to debug? 

Thank you.

**Comment by spasekovachev** [comment]
Hallo @SohanTirpude,
the log that I initially provided it's the complete log which I have. 
Best regards

**Comment by SohanTirpude** [comment]
Hello @spasekovachev,

The log you provided from that it is clear that it is failing to parse one of the cli command, but which command it is not clear. Because you did not share the full output. 

Another thing is I tried to replicate the issue with mock device, but I am not getting this issue, this may be because as you mentioned that this issue is seen on NXOS device configured with segment routing and I don't have such specific configurational mock device. 

Maybe, if you are not comfortable to share the whole device output here in open internet, you may share it to this CISCO confidential email address: `pyats-support-ext@cisco.com`

Or, if you can, you may create the recording of your device output using [Unicon.playback](https://pubhub.devnetcloud.com/media/unicon/docs/playback/index.html) and share with us on above-mentioned email address.

Kindly let me know.

Thank you.

**Comment by SohanTirpude** [comment]
Hello @spasekovachev,

If you are not ready to share the complete log then I am afraid I can not help you. Hence, I am closing this ticket. In future, if you are ready to share the logs, then kindly let me know.

Thank you.
