### ISSUE TITLE
Wrong parameter order in documentation

### ISSUE THREAD

**Issue by joabda** [CiscoTestAutomation/genielibs#141]
# Description
The documentation for [configure_interface_interfaces_on_port_channel](https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/apis/configure_interface_interfaces_on_port_channel) shows that `interfaces` comes before `channel_group` when in fact it's the reverse order.

https://github.com/CiscoTestAutomation/genielibs/blob/177526b85257993fcad7f184985268835f1f836a/pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/interface/configure.py#L1441-L1442

**Comment by sumsehga** [comment]
Kindly give sometime analyze your issue and get back to you.

**Comment by sumsehga** [comment]
Hi ,
Since genieparser is community driven, would you like to contribute to the library by following [this](https://pubhub.devnetcloud.com/media/pyats-development-guide/docs/writeparser/writeparser.html#contributing-your-work-to-the-pyats-project) documentation.
Please let me know if you need any help during the process of PR creation.

**Comment by sumsehga** [comment]
Hi , 
I seen that you have already raised a PR for above issue .

PR link :https://github.com/CiscoTestAutomation/genielibs/pull/142

**Comment by joabda** [comment]
Yeah we can close this as the PR I raised fixes it
