### ISSUE TITLE
missing policy-map/class-map/service-policy for configuration

### ISSUE THREAD

**Issue by nielsvanhooy** [CiscoTestAutomation/genielibs#83]
Sorry if this is not the right place to ask a question.
i was looking into pyAts and genie to see if we perhaps can use this tool to parse/configure  policy-maps/class-maps and place service-policies on interfaces.

is this a feature that is upcoming perhaps?

**Comment by LukasMcClelland** [comment]
My sincere apologies Niels! 

I didn't realize this issue was assigned to me. Usually, these issues are tracked but this one fell through the cracks. 

Yes, you can definitely use this tool to accomplish those things. [Genieparser](https://github.com/CiscoTestAutomation/genieparser) is where we keep our parsers and this repo is where we keep our APIs.  Hopefully, you'll find the functionality that you're looking for in both. But, if there's something missing, then please make the change and feel free contribute your code in PR!

**Comment by LukasMcClelland** [comment]
> is this a feature that is upcoming perhaps?

For the most part, our team sees to the underlying infrastructure and functionality of pyATS and Genie. For features like this that could perhaps be made into an API or 2, we like to ask people if they're interested in contributing something like this themselves

**Comment by LukasMcClelland** [comment]
I'll close this issue for now and if you'd like to contact me, then please feel free to email me at lumcclel@cisco.com or you can find me on Webex too. 

Thanks again for your help on the Huawei plugin for Unicon! 👍
